### ISSUE TITLE
consider linking https://github.com/ralphtheninja/open-funding

### ISSUE THREAD

**Issue by matkoniecz** [nayafia/microgrants#31]
https://github.com/ralphtheninja/open-funding is more focused ("funding open source projects") so probably it would not be useful to copy programs, but maybe it would be useful to link it?

**Comment by matkoniecz** [comment]
If that is a good idea - let me know and I will try making a PR.

**Comment by nayafia** [comment]
Hi @matkoniecz, thanks for flagging! I haven't been sure what to do with open source grant programs, because - given my line of work - I'm aware of so many, but I don't want to overwhelm this list (which is not OSS-focused).

I think it'd help to add a section to https://github.com/nayafia/lemonade-stand instead, with links to these resources.

If you want to take a stab at opening a PR over there, it'd mean:

1. Add a "Related resources" section to the appendix, i.e.:

```APPENDIX: [Related resources](#related-resources) // [Contributing to this guide](#contributing-to-this-guide) // [License & attribution](#license-and-attribution) ```

2. Add a bit of intro text + links to these guides:
* https://github.com/ralphtheninja/open-funding
* https://github.com/fredexed/crypto-funding-ops (another guide I find myself linking to)

WDYT? No worries if you don't have time, I'll do it either way, but thought I'd see if you're interested first, since it's your idea 😊

**Comment by matkoniecz** [comment]
I opened https://github.com/nayafia/lemonade-stand/pull/132 - I think that more inline linking would be better

I still think that linking here entire https://github.com/ralphtheninja/open-funding would be better as it links specific projects (what better matches microgrants) while https://github.com/nayafia/lemonade-stand is far more general

**Comment by nayafia** [comment]
thx! merged that PR.

**Comment by matkoniecz** [comment]
I still think that linking other lists of (micro)grants like https://github.com/ralphtheninja/open-funding#grants from here would be a good idea
